# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='country',
            field=models.CharField(max_length=2000),
        ),
    ]
